test2/delivery_form/urls.py
from django.urls import path
from .views import *

app_name = 'delivery'

urlpatterns = [
    path('', ItemList.as_view(), name='list'),
    path('create/', ItemCreate.as_view(), name='create'),
    path('delete/<int:pk>/', ItemDelete.as_view(), name='delete'),
    path('update/<int:pk>/', ItemUpdate.as_view(), name='update'),
    path('formset/', formset, name='formset'),
]

test2/test2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('delivery_form/', include('delivery_form.urls')),
    path('', RedirectView.as_view(url='/delivery_form/'))
]

test2/delivery_form/models.py
from email.policy import default
from enum import unique
from random import choices
from django.db import models
from django.core.validators import MinLengthValidator, MinValueValidator


class Choices(models.Model):
    choice = models.CharField(max_length=50, unique=True, blank=True)

    def __str__(self):
        return f'{self.choice}'


class Item(models.Model):
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=50)
    delivery_date = models.DateField(
        auto_now=False, auto_now_add=False, null=True)
    attachment = models.FileField(upload_to=None, max_length=100, blank=True)
    pickup_loc_fs = models.ManyToManyField(Choices)

    def __str__(self):
        return f'name: {self.name} type: {self.type} delivery_date: {self.delivery_date} attachment: {self.attachment} pickup_locs_fs: {self.pickup_loc_fs}'

test2/delivery_form/forms.py
from django import forms
from .models import Item
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.widgets import CheckboxSelectMultiple
from django.forms import modelformset_factory 

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'
        widgets = {'delivery_date': AdminDateWidget(
            attrs={'type': 'date'}), 'pickup_loc_fs': CheckboxSelectMultiple()}

ItemFormSet = modelformset_factory(Item, form=ItemForm)

test2/delivery_form/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView
from .models import Item
from django.urls import reverse, reverse_lazy
from django.contrib.admin.widgets import AdminDateWidget
from .forms import ItemForm, ItemFormSet
from django.forms.widgets import CheckboxSelectMultiple
# Create your views here.


class ItemCreate(CreateView):
    model = Item
    success_url = reverse_lazy('delivery:list')
    form_class = ItemForm

    

class ItemList(ListView):
    model = Item


class ItemDelete(DeleteView):
    model = Item
    success_url = reverse_lazy('delivery:list')


class ItemUpdate(UpdateView):
    model = Item
    fields = '__all__'
    success_url = reverse_lazy('delivery:list')


def formset(request):  
    formset = ItemFormSet()
    if request.method == 'POST':
        formset = ItemFormSet(request.POST)
        formset.save()

    return render(request, 'delivery_form/item_form.html', {'formset': formset})

test2/delivery_form/templates/delivery_form/delivery.html
{% extends 'base.html' %}


{% block content %}

    {% for item in object_list %}

        {{item}}
    
    {% endfor %}
    

{% endblock content %}
    

test2/delivery_form/templates/delivery_form/item_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
    <h1>are you sure you want delete this item</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="DA" />
    </form>
{% endblock content %}
    

test2/delivery_form/templates/delivery_form/item_form.html
{% extends 'base.html' %}


{% block content %}
<form method='POST'>
    {% csrf_token %}
    {{formset.as_p}}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

{% endblock content %}
    

test2/delivery_form/templates/delivery_form/item_list.html
{% extends 'base.html' %}


{% block content %}
    {% if object_list %}
        {% for item in object_list %}

            <p>{{item}} ||<a href="/delivery_form/delete/{{item.id}}">delete</a>||<a href="/delivery_form/update/{{item.id}}">edit</a></p>
        
        {% endfor %}
    {% else %}
        <h4>empty list</h4>
    {% endif %}   
{% endblock content %}
    

test2/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body>

    <p><b>above block</b></p>
    <a href="{% url 'delivery:create' %}">create item</a>
    {% block content %}
        <p>inside block</p>
    {% endblock content %}
    <a href="{% url 'delivery:formset' %}">formset</a>

</body>
</html>